import { Link } from 'react-router-dom';

export default function Terms() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold text-gray-900 mb-8">Terms of Service</h1>
      
      <div className="prose prose-indigo max-w-none">
        <p className="text-gray-500 mb-6">Last updated: August 2026</p>
        
        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 mb-3">1. Acceptance of Terms</h2>
          <p className="text-gray-600 leading-relaxed">
            By accessing or using ReadMyCode, you agree to be bound by these Terms of Service. 
            If you do not agree to these terms, please do not use our service.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 mb-3">2. Description of Service</h2>
          <p className="text-gray-600 leading-relaxed">
            ReadMyCode is an AI-powered documentation generator that analyzes GitHub repositories 
            to automatically create READMEs, API documentation, flowcharts, architecture diagrams, 
            function explanations, and debugging assistance.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 mb-3">3. User Accounts</h2>
          <p className="text-gray-600 leading-relaxed">
            You are responsible for maintaining the confidentiality of your account credentials. 
            You agree to accept responsibility for all activities that occur under your account.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 mb-3">4. Repository Access</h2>
          <p className="text-gray-600 leading-relaxed">
            When you provide a GitHub repository URL or upload code, you grant ReadMyCode permission 
            to access, analyze, and process that code solely for the purpose of generating documentation. 
            We do not store your source code permanently.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 mb-3">5. AI-Generated Content</h2>
          <p className="text-gray-600 leading-relaxed">
            Documentation generated by our AI is provided "as is." While we strive for accuracy, 
            you are responsible for reviewing and verifying all generated content before use.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 mb-3">6. Limitation of Liability</h2>
          <p className="text-gray-600 leading-relaxed">
            ReadMyCode shall not be liable for any indirect, incidental, special, or consequential 
            damages resulting from the use or inability to use the service.
          </p>
        </section>
      </div>

      <div className="mt-12 pt-8 border-t border-gray-200">
        <p className="text-gray-500 text-sm">
          Questions? <Link to="/help" className="text-indigo-600 hover:underline">Contact support</Link>
        </p>
      </div>
    </div>
  );
}